#!/bin/bash
#PBS -l select=1:ncpus=4:mem=16gb:ngpus=1:gpu_type=L40S
#PBS -l walltime=01:00:00
#PBS -N har_transformer
#PBS -o /rds/general/user/ys5320/home/har_project/logs/transformer_train.log
#PBS -e /rds/general/user/ys5320/home/har_project/logs/transformer_train.err

cd /rds/general/user/ys5320/home/har_project/code

source /rds/general/user/ys5320/home/anaconda3/etc/profile.d/conda.sh
conda activate eeg

python 02_Transformer_train.py